#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE gogs;
    CREATE DATABASE drone;
    GRANT ALL PRIVILEGES ON DATABASE gogs TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE drone TO ${POSTGRES_USER};
EOSQL
